### ISSUE TITLE
[BUG] Secrets.json can not be persisted properly via docker

### ISSUE THREAD

**Issue by chrisbennight** [SillyTavern/SillyTavern#2092]
### Environment

🐧 Linux

### System

Ubuntu 22.04, Docker 26.01

### Version

1.11.7

### Desktop Information

Running using the following docker compose (volumes redacted)

```
version: "3.7"
services:
  sillytavern:
    restart: unless-stopped
    container_name: sillytavern
    hostname: sillytavern
    image: ghcr.io/sillytavern/sillytavern:release
    ports:
      - "8000:8000"
    volumes:
      - "st-config:/home/node/app/config"
      - "st-data:/home/node/app/public/user"
      - "st-tpe:/home/node/app/public/scripts/extensions/third-party"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

### Describe the problem

API keys are not properly persisted in docker, because the secrets.json is not persisted.

In the exemplar docker config secrets.json is in the app root, not config directory, so it isn't saved.

If a file mount point is added, such as `"/docker/sillytavern/secrets.json:/home/node/app/secrets.json"` then the app returns errors because the file handle isn't opened and edited, but a tmp file created and the moved over.  This isn't compatible with docker file mounts though.

Error:
```
Error: EBUSY: resource busy or locked, rename '/home/node/app/secrets.json.3143730341' -> '/home/node/app/secrets.json'
    at Object.renameSync (node:fs:1032:3)
    at writeFileSync (/home/node/app/node_modules/write-file-atomic/lib/index.js:252:8)
    at writeSecret (/home/node/app/src/endpoints/secrets.js:63:5)
    at /home/node/app/src/endpoints/secrets.js:191:5
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/app/node_modules/express/lib/router/route.js:149:13)
    at /home/node/app/node_modules/body-parser/lib/read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (/home/node/app/node_modules/raw-body/index.js:238:16)
    at done (/home/node/app/node_modules/raw-body/index.js:227:7)
```

As it stands there is no way to persist api keys using docker.  Moving the secrets.json to the config directory, or even making a new /secrets/ directory that houses the file (and thus allows path instead of file mounts) would fix the issue.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)
