### ISSUE TITLE
[BUG] Can't connect to  Ollama ST docker.

### ISSUE THREAD

**Issue by razvanab** [SillyTavern/SillyTavern#2647]
### Environment

🪟 Windows

### System

MS Edge 127.0.2651.98 ,Windows 11, Docker Desktop 4.33.1 (161083) 

### Version

SillyTavern 1.12.4

### Desktop Information

Ollama  0.3.4

### Describe the problem

Can't connect to ollama from Docker SillyTavern. 
```
2024-08-11 23:41:17 sillytavern  | Trying to connect to API: {
2024-08-11 23:41:17 sillytavern  |   api_server: 'http://127.0.0.1:11434/',
2024-08-11 23:41:17 sillytavern  |   api_type: 'ollama',
2024-08-11 23:41:17 sillytavern  |   legacy_api: false
2024-08-11 23:41:17 sillytavern  | }
2024-08-11 23:41:17 sillytavern  | FetchError: request to http://127.0.0.1:11434/api/tags failed, reason: connect ECONNREFUSED 127.0.0.1:11434
2024-08-11 23:41:17 sillytavern  |     at ClientRequest.<anonymous> (/home/node/app/node_modules/node-fetch/lib/index.js:1505:11)
2024-08-11 23:41:17 sillytavern  |     at ClientRequest.emit (node:events:519:28)
2024-08-11 23:41:17 sillytavern  |     at Socket.socketErrorListener (node:_http_client:500:9)
2024-08-11 23:41:17 sillytavern  |     at Socket.emit (node:events:519:28)
2024-08-11 23:41:17 sillytavern  |     at emitErrorNT (node:internal/streams/destroy:169:8)
2024-08-11 23:41:17 sillytavern  |     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
2024-08-11 23:41:17 sillytavern  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2024-08-11 23:41:17 sillytavern  |   type: 'system',
2024-08-11 23:41:17 sillytavern  |   errno: 'ECONNREFUSED',
2024-08-11 23:41:17 sillytavern  |   code: 'ECONNREFUSED'
2024-08-11 23:41:17 sillytavern  | }
```

### Additional info

After hours of digging around and trying a lot of stuff, this was the solution:

Set OLLAMA_HOST variable to:
OLLAMA_HOST http://127.0.0.1:11434

In docker-compose.yml add
    ports:
      - "8000:11434"
    extra_hosts:
      - "host.docker.internal:host-gateway"

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by razvanab** [comment]
I think there should be an easier solution built into the SillyTavern Docker image.

**Comment by Cohee1207** [comment]
Not a bug. You are responsible for setting up your backend. And I don't know what solution you are proposing.

**Comment by razvanab** [comment]
By including the ollama port in the Docker configuration, perhaps. In order to avoid having to spend hours digging for a solution or make the SillyTavern Docker installation documentation better., I'm only stating that it took me several hours to figure this out.

**Comment by Cohee1207** [comment]
> By including the ollama port in the Docker configuration, perhaps.

Why should it do so? SillyTavern does not favor any particular backend. The proposed Docker configuration is for the frontend itself. If you wish to containerize everything you host, we assume that you know what you're doing.

> make the SillyTavern Docker installation documentation better

Docker documentation was contributed by our users. You are free to propose changes by sending pull requests to the docs repository (it's just markdown files): https://github.com/SillyTavern/SillyTavern-docs

**Comment by razvanab** [comment]
I understand. Thanks.

**Comment by hdahmou** [comment]
@razvanab  Just to confirm my understanding: when running a SillyTavern container on a Windows host with an Ollama backend accessible at http://127.0.0.1:11434/, the docker-compose.yml file would look like this:
```
version: "3"
services:
  sillytavern:
    build: ..
    container_name: sillytavern
    hostname: sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    ports:
      - "8000:8000"
    volumes:
      - "./config:/home/node/app/config"
      - "./data:/home/node/app/data"
      - "./plugins:/home/node/app/plugins"
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=http://127.0.0.1:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
because I still get the error: ```FetchError: request to http://127.0.0.1:11434/api/tags failed, reason: connect ECONNREFUSED 127.0.0.1:11434```
I admit I didn't add the ```8000:11434``` mapping, because (I think) it route traffic from the host's port 8000 to the container's port 11434, making SillyTavern UI inaccessible.

**Comment by bee-san** [comment]
I cheated and put Ollama into the compose itself, as ST lets you download models.

Use `http://ollama:11434/` in the API section

```
version: "3"
services:
  sillytavern:
    build: ..
    container_name: sillytavern
    hostname: sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    ports:
      - "8069:8000"
    volumes:
      - "./config:/home/node/app/config"
      - "./data:/home/node/app/data"
      - "./plugins:/home/node/app/plugins"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ollama

  ollama:
    container_name: ollama
    hostname: ollama
    image: ollama/ollama:latest
    volumes:
      - "./ollama:/root/.ollama"
    restart: unless-stopped
```
