### ISSUE TITLE
[BUG] All settings wiped after upgrade

### ISSUE THREAD

**Issue by Ultraguy24** [SillyTavern/SillyTavern#2695]
### Environment

🐋 Docker

### System

Debian 12 / Docker 27.1.2

### Version

1.12.4

### Desktop Information

Staging Branch

### Describe the problem

Every time I refresh my container, it clears all data like a fresh install. I update build, point it to the same bind points but it then proceeds to clear them instead of just load them. I lose everything from settings within sleepytavern, characters, conversations, etc. I usually have to backup everything each time I want to check for a slightly newer version. Can produce more information request.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Docker containers are **stateless by design**. To have data persistence, you have to use volumes. Please see examples in the readme or docs, or use a proposed docker-compose file.

https://docs.sillytavern.app/installation/docker/
https://github.com/SillyTavern/SillyTavern/blob/release/docker/docker-compose.yml
https://github.com/SillyTavern/SillyTavern?tab=readme-ov-file#volume-mappings

**Comment by mtaanquist** [comment]
I just had the same happen to my Docker container, and I am using volumes for my data and config directories.

My docker-compose.yml:
```yml
services:
  sillytavern:
    build: ..
    container_name: sillytavern
    hostname: sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    ports:
      - "13013:8000"
    volumes:
      - ./config:/home/node/app/config
      - ./data:/home/node/app/data
      - ./plugins:/home/node/app/plugins
    restart: unless-stopped
```
Note: the port's just because 8000 was already in use by other things, I run it behind an nginx reverse proxy.

To upgrade my container, I did the following series of commands:
```bash
$ docker compose down
$ docker compose pull
$ docker compose up -d
```

When the container was back up and running, I was presented with a new user screen, and all my API keys and stuff was gone. The `config/config.yml` file was untouched though, so my whitelist and listen settings were still OK.
