### ISSUE TITLE
[BUG] Unable to click on right hand side in iOS due to `<script id="gallery"` having a display style of `display: block`

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [SillyTavern/SillyTavern#2907]
### Environment

🐋 Docker

### System

Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1

### Version

1.12.5

### Desktop Information

- Generation: LocalAI (OpenAI like)
- Git hash: 3e67f559d43b53faeb4a32b63c8b89391f0b7248
    -  Minor modification to support old ios as discussed in another issue #1358

### Describe the problem

On iOS I was unable to select anything on the right of the screen (buttons etc). I hooked up the debugger and saw this element on the right:

<img width="300" alt="Shot01" src="https://github.com/user-attachments/assets/3949b02c-24ca-4c43-aa38-11997513890a">

(Please ignore the discord theme this issue happens on vanilla too)

Tracking this down revealed the following:

<img width="973" alt="Screenshot 2024-09-27 at 14 01 59" src="https://github.com/user-attachments/assets/74f37569-f71d-4b2c-81a0-956298bcaab6">

Which shows that the script element

```html
<script id="gallery" type="module" src="/scripts/extensions/gallery/index.js" async=""></script>
```

Which shows that this script element has the style `display: block`

Which comes from style.css:5348

```css
@media screen and (max-width: 1000px) {
    #gallery {
        display: block;
        width: 100vw;
        height: 100vh;
        z-index: 9999;
    }

    .draggable {
        display: block;
        width: 100vw;
        height: 100vh;
        z-index: 9999;
    }
}
```

This makes the whole of the right side unclickable (for buttons and the menus). Removing this CSS results in working buttons on the right hand side

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)
