### ISSUE TITLE
[BUG] Website breaks in Firefox

### ISSUE THREAD

**Issue by KTibow** [SillyTavern/SillyTavern#3126]
### Environment

🐧 Linux

### System

Firefox 132.0.1 (64-bit) on Fedora

### Version

-

### Describe the problem

When you go to https://sillytavern.app/ in Firefox, the website is centered around the top edge of the screen instead of the center. This problem does not occur in Chromium.

### Additional info

![image](https://github.com/user-attachments/assets/6bf819e7-0fb7-4bdd-97c9-62f15d8edb69)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
@RossAscends take a look, please.

**Comment by Wolfsblvt** [comment]
The issue is with with using `position: absolute`, setting all four directions to `0` and then using `margin: auto`.

Dabbled a bit with the dev tools, and think using flex for the display is much better anyway.

The following should do the trick.
I marked with comments which CSS stuff to remove.

```css
body {
    height: 100%;
    justify-content: center;
    align-content: center;
    display: flex;
    flex-flow: wrap;
    /*
    height: 100svh;
    height: calc(var(--doc-height) - 1px);
    */
}
.bodywrap {
    /*
    margin: auto auto;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    position: absolute;
    */
}
```

Not sure if I have access to the website, can't find the repo for it, @Cohee1207.
