### ISSUE TITLE
[BUG] Unable to access the service locally by ip address+port of cloud server after the Docker deployment on the Linux system of the cloud server

### ISSUE THREAD

**Issue by Kendr1ckFu** [SillyTavern/SillyTavern#3446]
### Environment

🐧 Linux

### System

Linux version 5.10.134-18.al8.x86_64， Docker version 26.1.4, build 5650f9b

### Version

SillyTavern 1.12.11 the latest release

### Describe the problem

I followed the official documentation completely for the Docker deployment on the Linux system of the cloud server. 
After deployment, when accessing the server IP:port locally, it shows the context.
> **Forbidden: Connection attempt from {{my_local_ip}}. If you are attempting to connect, please add your IP address in the whitelist or disable whitelist mode in config.yaml in the root of the SillyTavern folder.**

Here is the content of /docker/config/config.yaml,
```yaml
dataRoot: ./data
cardsCacheCapacity: 100
listen: true
protocol:
  ipv4: true
  ipv6: false
dnsPreferIPv6: false
autorunHostname: auto
port: 8000
autorunPortOverride: -1
whitelistMode: true
enableForwardedWhitelist: true
whitelist:
  - 0.0.0.0
  - ::1
  - 127.0.0.1
  - 172.19.0.1
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
basicAuthMode: false
basicAuthUser:
  username: user
  password: password
enableCorsProxy: false
requestProxy:
  enabled: false
  url: socks5://username:password@example.com:1080
  bypass:
    - localhost
    - 127.0.0.1
enableUserAccounts: false
enableDiscreetLogin: false
autheliaAuth: false
perUserBasicAuth: false
sessionTimeout: 86400
```
In the value of whitelist, I have added the Docker gateway address and all possible IPv4 access permissions, and modified the configuration for allowing remote connections as per the documentation. However, I am still unable to access the service locally.

### Please tick the boxes

- [x] I have explained the issue clearly, and I included all relevant info
- [x] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)
- [x] I confirm that my issue is not related to third-party content, unofficial extension or patch. If in doubt, check with a new [user account](https://docs.sillytavern.app/administration/multi-user/) and with extensions disabled
