### ISSUE TITLE
[BUG] Client IP Detection Fails Behind Caddy Reverse Proxy

### ISSUE THREAD

**Issue by Zhen-Bo** [SillyTavern/SillyTavern#3503]
### Environment

🐋 Docker

### System

Docker version 27.5.1, build 9f9e405; Docker Compose version v2.32.4

### Version

1.12.12

### Describe the problem

I've discovered an issue with SillyTavern's IP detection when running behind a Caddy reverse proxy in a Docker environment. 
The application is unable to correctly identify the real client IP addresses of visitors.

**Current Behavior:**
- All connections show as local network IP
- Log shows "New connection from {local network IP}; User Agent: ..." regardless of actual source IP
- This affects the login attempt rate limiting functionality
- When one user triggers the rate limit through failed login attempts, it blocks all other users because they're all seen as coming from the same internal IP

**Environment Setup:**
<details>
<summary>SillyTavern config.yaml</summary>

```yaml
dataRoot: ./data
cardsCacheCapacity: 100
listen: true
listenAddress:
  ipv4: 0.0.0.0
  ipv6: "[::]"
protocol:
  ipv4: true
  ipv6: true
dnsPreferIPv6: false
autorunHostname: auto
port: 8000
autorunPortOverride: -1
whitelistMode: false
enableForwardedWhitelist: true
whitelist:
  - ::1
  - 127.0.0.1
basicAuthMode: false
basicAuthUser:
  username: 
  password: 
enableCorsProxy: false
requestProxy:
  enabled: false
  url: socks5://username:password@example.com:1080
  bypass:
    - localhost
    - 127.0.0.1
enableUserAccounts: true
enableDiscreetLogin: false
autheliaAuth: false
perUserBasicAuth: false
minLogLevel: 0
sessionTimeout: -1
cookieSecret: {cookieSecret}
disableCsrfProtection: false
securityOverride: false
autorun: true
avoidLocalhost: false
backups:
  common:
    numberOfBackups: 50
  chat:
    enabled: true
    maxTotalBackups: -1
    throttleInterval: 10000
thumbnails:
  enabled: true
  format: jpg
  quality: 95
  dimensions:
    bg:
      - 160
      - 90
    avatar:
      - 96
      - 144
allowKeysExposure: false
skipContentCheck: false
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
requestOverrides: []
extensions:
  enabled: true
  autoUpdate: true
  models:
    autoDownload: true
    classification: Cohee/distilbert-base-uncased-go-emotions-onnx
    captioning: Xenova/vit-gpt2-image-captioning
    embedding: Cohee/jina-embeddings-v2-base-en
    speechToText: Xenova/whisper-small
    textToSpeech: Xenova/speecht5_tts
enableDownloadableTokenizers: true
promptPlaceholder: "[Start a new chat]"
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
mistral:
  enablePrefix: false
ollama:
  keepAlive: -1
  batchSize: -1
claude:
  enableSystemPromptCache: false
  cachingAtDepth: -1
enableServerPlugins: false
enableServerPluginsAutoUpdate: true

```
</details>

<details>
<summary>SillyTavern Docker Compose</summary>

```yaml
services:
  SillyTavern:
    container_name: SillyTavern
    restart: unless-stopped
    image: ghcr.io/sillytavern/sillytavern:latest
    ports:
      - "8000:8000"
    volumes:
      - ./plugins:/home/node/app/plugins:rw
      - ./config:/home/node/app/config:rw
      - ./data:/home/node/app/data:rw
      - ./extensions:/home/node/app/public/scripts/extensions/third-party:rw
      - ./public/login.html:/home/node/app/public/login.html
      - ./public/img/background.jpg:/home/node/app/public/img/background.jpg
      - ./public/scripts/login.js:/home/node/app/public/scripts/login.js
    networks:
      - caddy
      - internal_network # disable this still dislpay local network ip

networks:
  internal_network: # disable this still dislpay local network ip
    driver: bridge # disable this still dislpay local network ip
  caddy:
    external: true
```
</details>

<details>
<summary>Caddy Docker Compose</summary>

```yaml
services:
  caddy:
    container_name: caddy
    build: .
    restart: always
    networks:
      - caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/:/etc/caddy/
      - ./site/:/srv
      - ./data:/data
      - ./config:/config
      - ./logs:/var/log/caddy
    env_file:
      - ./.env

networks:
  caddy:
    external: true
```
</details>

<details>
<summary>Caddyfile Dockerfile</summary>

```Dockerfile
FROM caddy:builder AS builder
RUN xcaddy build --with github.com/caddy-dns/cloudflare --with github.com/WeidiDeng/caddy-cloudflare-ip

FROM caddy:latest
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
</details>

<details>
<summary>Caddyfile Configuration</summary>

```groovy
{
	email {cloudflare_mail@example.com}
	acme_dns cloudflare {env.CLOUDFLARE_API_TOKEN}

	servers {
		trusted_proxies cloudflare {
			interval 12h
			timeout 15s
		}
	}
}

(logging) {
	log {
		output file /var/log/caddy/caddy.log 
		format json
	}
}

{DOMAIN.com}, *.{DOMAIN.com} {
	import logging
	tls {
		protocols tls1.3
	}

	header {
		X-Frame-Options "SAMEORIGIN"
		X-XSS-Protection "1; mode=block"
		X-Content-Type-Options "nosniff"
		Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
	}

	@sillytavernHost {
		host sillytavern.{DOMAIN.com}
	}
	handle @sillytavernHost {
		reverse_proxy http://sillytavern:8000 {
			header_up X-Forwarded-For {header.CF-Connecting-IP}
			header_up X-Real-IP {header.CF-Connecting-IP}
			header_up Remote-Addr {header.CF-Connecting-IP}

			transport http {
				dial_timeout 10s
				response_header_timeout 30s
				read_buffer 4096
				write_buffer 4096
			}
		}
	}

	@apexHost {
		host {DOMAIN.com}
	}
	handle @apexHost {
		respond "404 Not Found1"
	}

	handle_errors {
		respond "{http.error.status_code} {http.error.status_text}"
	}
}

```
</details>

**Expected Behavior:**
- SillyTavern should properly detect and log the original client IP addresses
- Rate limiting should work correctly on the correct IP adress
- Access logs should show the actual source IP of visitors

### Additional info

I've discovered some interesting behavior regarding IP handling and whitelisting:

**Current Implementation Findings:**
- When `whitelistMode: true` is set with the following configuration:
  ```javascript
  enableForwardedWhitelist: true
  whitelist:
    - {local network ip} // e.g. 172.x.x.x
  ```
- The system still displays the local network IP in logs
- However, the whitelist blocking functionality works correctly

**Code Investigation:**
I've identified two relevant files that handle IP detection:

1. In `src/express-common.js`:
- Current `getIpFromRequest` implementation might need modification
- Should consider implementing `req.headers['x-real-ip']` check
- This would help properly identify the actual client IP

2. In `src/middleware/whitelist.js`:
   - The `getForwardedIp` function should only check `req.headers['x-forwarded-for']` and does not need an additional check for `x-real-ip`.
   - This is because when `whitelistMode === true && !whitelist.some(x => ipMatching.matches(clientIp, ipMatching.getMatch(x))`, it will already perform the necessary checks.

After implementing the `req.headers['x-real-ip']` check in `getIpFromRequest`, SillyTavern will get the correct client IP instead of the reverse proxy's IP.

### Please tick the boxes

- [x] I have explained the issue clearly, and I included all relevant info
- [x] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)
- [x] I confirm that my issue is not related to third-party content, unofficial extension or patch. If in doubt, check with a new [user account](https://docs.sillytavern.app/administration/multi-user/) and with extensions disabled
