### ISSUE TITLE
[BUG] <title>User accounts not working

### ISSUE THREAD

**Issue by pkm90** [SillyTavern/SillyTavern#3665]
### Environment

🪟 Windows

### System

Windows

### Version

SillyTavern 1.12.12

### Desktop Information

Silly Tavern being run in Pinokio

### Describe the problem

Steps taken:
- Followed docs to enable multi-user: https://docs.sillytavern.app/administration/multi-user/
- Ensured changes are in correct config file (errors made in this config file will show up while silly tavern is starting up)
- Added empty new users
- Restarted both pinokio and silly tavern

Despite doing this, I don't see any differences when running silly tavern. It seems to go directly to the data/default-user. Tried modifying configs to see something but nothing comes up requiring auth or allowing me to select which user. set enableDiscreetLogin to false, set basicAuthMode to true, etc.

See below for config file details:
dataRoot: ./data
cardsCacheCapacity: 100
listen: false
protocol:
  ipv4: true
  ipv6: false
dnsPreferIPv6: false
autorunHostname: auto
port: 8000
autorunPortOverride: -1
whitelistMode: false
enableForwardedWhitelist: true
whitelist:
  - ::1
  - 127.0.0.1
basicAuthMode: true
basicAuthUser:
  username: user
  password: password
enableCorsProxy: false
requestProxy:
  enabled: false
  url: socks5://username:password@example.com:1080
  bypass:
    - localhost
    - 127.0.0.1
enableUserAccounts: true
enableDiscreetLogin: false
autheliaAuth: false
perUserBasicAuth: true
sessionTimeout: 86400
cookieSecret: rCmQ5V44QVj0MaZ8F8LPv75ixQOsk6GR7hT7j00AB64AKNsiKGFDCoIh5IwPDkIfbUwosHGRELIW8DzySAAZEg==
disableCsrfProtection: false
securityOverride: false
autorun: true
avoidLocalhost: false
backups:
  common:
    numberOfBackups: 50
  chat:
    enabled: true
    maxTotalBackups: -1
    throttleInterval: 10000
thumbnails:
  enabled: true
  format: jpg
  quality: 95
  dimensions:
    bg:
      - 160
      - 90
    avatar:
      - 96
      - 144
allowKeysExposure: false
skipContentCheck: false
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
requestOverrides: []
enableDownloadableTokenizers: true
extras: {}
promptPlaceholder: "[Start a new chat]"
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
mistral:
  enablePrefix: false
ollama:
  keepAlive: -1
  batchSize: -1
claude:
  enableSystemPromptCache: false
  cachingAtDepth: -1
enableServerPlugins: false
extensions:
  enabled: true
  autoUpdate: true
  models:
    autoDownload: true
    classification: Cohee/distilbert-base-uncased-go-emotions-onnx
    captioning: Xenova/vit-gpt2-image-captioning
    embedding: Cohee/jina-embeddings-v2-base-en
    speechToText: Xenova/whisper-small
    textToSpeech: Xenova/speecht5_tts
listenAddress:
  ipv4: 0.0.0.0
  ipv6: "[::]"
minLogLevel: 0
enableServerPluginsAutoUpdate: true

### Additional info

**Edit: To be very clear, the below error doesn't exist anymore. It's just there to show that I'm using the correct config file.**

Using correct config file, here's what I saw when I copied+pasted the multi-user config to bottom of config file instead of checking to see if it exists first:

![Image](https://github.com/user-attachments/assets/86d99c8e-455d-4dba-9436-fdea2c198e0e)

### Please tick the boxes

- [x] I have explained the issue clearly, and I included all relevant info
- [x] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)
- [x] I confirm that my issue is not related to third-party content, unofficial extension or patch. If in doubt, check with a new [user account](https://docs.sillytavern.app/administration/multi-user/) and with extensions disabled

**Comment by Cohee1207** [comment]
You have corrupted the default config. Please use `git reset --hard` to restore the original default config.

**Comment by pkm90** [comment]
> You have corrupted the default config. Please use `git reset --hard` to restore the original default config.

I'm on a new pc so I don't have git installed...but I'm assuming you just want me to reset the file to it's previous state and test. Here's my findings:

Replaced original file with the default...didn't work...
Uninstalled+reinstalled silly tavern, changed config file, didn't work...

**Comment by Wolfsblvt** [comment]
I no version of the default config.yaml file is the `enableUserAccounts` value as deep as line 96.
I cannot really figure out why it would be duplicated either.

Can you make sure that your config.yaml is exactly like this?
https://github.com/SillyTavern/SillyTavern/blob/staging/default/config.yaml

**Comment by pkm90** [comment]
> I no version of the default config.yaml file is the `enableUserAccounts` value as deep as line 96. I cannot really figure out why it would be duplicated either.
> 
> Can you make sure that your config.yaml is exactly like this? https://github.com/SillyTavern/SillyTavern/blob/staging/default/config.yaml

Hello, thanks for the reply. You misunderstood the point of me adding the screenshot. I added it just to show that I'm using the correct config file, that specific error doesn't exist anymore.

For your suggestion, yes, I tried this already. I then modified the parameters having to do with user auth, but no success...I still don't get any login/user-selection screen.

**Comment by Wolfsblvt** [comment]
If the image and error message from above is not your actual error message you run into with your setup and your config file, what is the exact error when you try to start SillyTavern?

Details do help.

**Comment by czyt** [comment]
same issue
```
sillytavern-1  | 2025-03-12T05:03:41.562087967Z 
sillytavern-1  | 2025-03-12T05:03:41.565191336Z [34mA friendly reminder that the following users are not password protected:[39m
sillytavern-1  | 2025-03-12T05:03:41.565305278Z [33mdefault-user[39m [31m(admin)[39m
sillytavern-1  | 2025-03-12T05:03:41.565462050Z 
sillytavern-1  | 2025-03-12T05:03:41.565568723Z Consider setting a password in the admin panel or by using the [34mrecover.js[39m script.
sillytavern-1  | 2025-03-12T05:03:41.565632586Z 
sillytavern-1  | 2025-03-12T05:03:41.565915939Z [31mIf you are not using basic authentication or whitelisting, you should set a password for all admin users.[39m
```
and the config
``` yaml
dataRoot: ./data
cardsCacheCapacity: 100
listen: false
listenAddress:
  ipv4: 0.0.0.0
  ipv6: "[::]"
protocol:
  ipv4: true
  ipv6: false
dnsPreferIPv6: false
autorunHostname: auto
port: 8000
autorunPortOverride: -1
whitelistMode: false
enableForwardedWhitelist: true
whitelist:
  - ::1
  - 127.0.0.1
basicAuthMode: false
basicAuthUser:
  username: gopher
  password: coder
enableCorsProxy: false
requestProxy:
  enabled: false
  url: socks5://username:password@example.com:1080
  bypass:
    - localhost
    - 127.0.0.1
enableUserAccounts: true
enableDiscreetLogin: true
autheliaAuth: false
perUserBasicAuth: false
minLogLevel: 0
sessionTimeout: -1
cookieSecret: QcPIs6XAT/NOkT+Swi68/9+opQb1enIrOEMJHGVwggsGhQzeKE3bts8ZhZ9akG89imes1HbU47ln/0oUB7AbZg==
disableCsrfProtection: false
securityOverride: false
autorun: true
avoidLocalhost: false
backups:
  common:
    numberOfBackups: 50
  chat:
    enabled: true
    maxTotalBackups: -1
    throttleInterval: 10000
thumbnails:
  enabled: true
  format: jpg
  quality: 95
  dimensions:
    bg:
      - 160
      - 90
    avatar:
      - 96
      - 144
allowKeysExposure: false
skipContentCheck: false
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
requestOverrides: []
extensions:
  enabled: true
  autoUpdate: true
  models:
    autoDownload: true
    classification: Cohee/distilbert-base-uncased-go-emotions-onnx
    captioning: Xenova/vit-gpt2-image-captioning
    embedding: Cohee/jina-embeddings-v2-base-en
    speechToText: Xenova/whisper-small
    textToSpeech: Xenova/speecht5_tts
enableDownloadableTokenizers: true
promptPlaceholder: "[Start a new chat]"
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
mistral:
  enablePrefix: false
ollama:
  keepAlive: -1
  batchSize: -1
claude:
  enableSystemPromptCache: false
  cachingAtDepth: -1
enableServerPlugins: false
enableServerPluginsAutoUpdate: true

```
I only enable userAcounts,but the default-user cannot login
```
enableUserAccounts: true
enableDiscreetLogin: true
```
