### ISSUE TITLE
[BUG] Docker pull via repo link fails in 1.7.3 but not 1.7.2

### ISSUE THREAD

**Issue by gamdud** [SillyTavern/SillyTavern#607]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes 

**Describe the bug**
Containerizing 1.7.3 from repo using
```
version: "3"
services:
  sillytavern:
    build: https://github.com/SillyTavern/SillyTavern.git#1.7.3
    container_name: sillytavern
    hostname: sillytavern
    image: sillytavern/sillytavern:latest
    ports:
      - "8001:8000"
    restart: unless-stopped
    volumes:
      - /home/darryl/llama/config:/home/node/app/config
      - /home/darryl/llama/config.conf:/home/node/app/config.conf
```
yields
```
failed to pull images of the stack: sillytavern Pulling sillytavern Warning WARNING: Some service image(s) must be built from source by running: docker compose build %s sillytavern 1 error occurred: * Error response from daemon: pull access denied for sillytavern/sillytavern, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
while the same docker-compose.yml for 1.7.2 works as expected.

**To Reproduce**
1. Confirm that 1.7.2 docker works by editing the above docker-compose.yml with 1.7.2 -> 1.7.3
2. Try with tag 1.7.3 and see the error message

**Expected behavior**
Sillytavern 1.7.3 getting pulled and then initializing

**Screenshots**
N/a

**Logs**
```
failed to pull images of the stack: sillytavern Pulling sillytavern Warning WARNING: Some service image(s) must be built from source by running: docker compose build %s sillytavern 1 error occurred: * Error response from daemon: pull access denied for sillytavern/sillytavern, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Desktop (please complete the following information):**
 - OS/Device: Debian 11
 - Environment: local
 - Docker version 20.10.22

**Additional context**
Only updating to 1.7.3 to see if Poe api got fixed

**Comment by gamdud** [comment]
One can automate the building step straight from the github repo link by specifying a github link in the `build:` key, so no dockerhub or ghcr involved:-) But anywho, it's fixed! I'll close the issue.

Turns out [it wasn't actually rebuilding on pull!](https://github.com/portainer/portainer/issues/6288). `pull_policy: build` after the `build:` line fixes this behavior. For anyone looking to self-host sillytavern via docker compose without having to manually rebuild, you can do:
```
version: "3"
services:
  sillytavern:
    build: https://github.com/SillyTavern/SillyTavern.git#1.7.3
    pull_policy: build
    container_name: sillytavern
    hostname: sillytavern
    image: sillytavern/sillytavern:latest
    ports:
      - "8001:8000"
    restart: unless-stopped
    volumes:
      - /path/to/llama/config:/home/node/app/config
      - /path/to/llama/config.conf:/home/node/app/config.conf
```
Which is also crucial if one wants to change ports without having to manually build the image and edit the source:-) Also note that the #1.7.3 tag is redundant.
